#!/usr/bin/env bash
# This script transfers a file from client to a server.

if [ $# -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Parameters
FILE_PATH="$1"
DEST_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$DEST_IP:~/"
