#!/usr/bin/env bash
# This script install NGINX web server

# install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# configure NGINX to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g'
/etc/nginx/sites-available/default

# restart NGINX
sudo service nginx restart
