#!/usr/bin/env bash
# This script installs NGINX web server and configures it

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow NGINX through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a custom Nginx configuration file
echo '
server {
    listen 80;
    server_name localhost;

    location / {
        return 200 "Hello World!";
    }
}
' | sudo tee /etc/nginx/sites-available/my_custom_site > /dev/null

# Enable the custom site
sudo ln -s /etc/nginx/sites-available/my_custom_site /etc/nginx/sites-enabled/

# Remove the default configuration
sudo rm /etc/nginx/sites-enabled/default

# Test the configuration
sudo nginx -t

# Restart NGINX
sudo systemctl restart nginx

