#!/usr/bin/env bash
# This script configures my Nginx server so that /redirect_me is redirecting to another page.
new_string="\	location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

# Backup the original configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Insert the new_string after the first uncommented 'server {' line found
sudo sed -i "/^[^#]*server {/a $new_string" /etc/nginx/sites-available/default

# Restart Nginx to apply chanes if configuration test passes
if sudo nginx -t; then
    sudo systemctl restart nginx
    echo "301"
else
    echo "Nginx configuration failed."
    exit 1
fi
