#!/usr/bin/env bash
# This script configures my Nginx server so that /redirect_me is redirecting to another page.
new_string="location /redirect_me {\n    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sed -i "s|location /redirect_me {.*}|$new_string|" /etc/nginx/sites-available/default
sudo systemctl restart nginx
