#!/usr/bin/env bash
# This bash script installs HAProxy on my load balancer server

# Update package repositories
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log	local0
    log /dev/log	local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log	global
    mode	http
    option	httplog
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 290494-web-01 52.72.75.91:80 check
    server 290494-web-02 18.234.107.142:80 check
EOF

# Restart HAProxy to apply the configuration
sudo systemctl restart haproxy
