#!/usr/bin/env bash
# This script pings an IP address passed as an argument

# check if an argument is passed
if [ $# -eq 0 ];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# extract the IP address from the argument.
ip_address=$1

# ping the IP address 5 times
ping_result=$(ping -c 5 "$ip_address")

# display the ping result
echo "$ping_result"