#!/usr/bin/env bash
# This script displays the PID, along with the process name, of process whose name contain the word 'bash'.

pids=$(pgrep -f bash)
for pid in $pids
do
    proc_name=$(cat /proc/"$pid"/comm)
    echo "$pid $proc_name"
done