#!/usr/bin/env bash
# This script displays all active IPv4 IPs on my machine.

for interface in /sys/class/net/*; do
    interface=$(basename "$interface")
    if [[ $(cat /sys/class/net/"$interface"/operstate) = "up" ]]
    then
        ip=$(ip -4 addr show "$interface" | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
        echo "$ip"
    fi
done
